# Generated by Django 3.2.25 on 2025-01-21 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0057_auto_20221118_2108'),
        ('users', '0025_user_is_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='artist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='music.artist'),
        ),
    ]
