# Generated by Django 3.2.25 on 2025-01-22 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tags', '0003_auto_20250117_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagcategory',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='tagcategory',
            name='input_type',
            field=models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple')], default='multiple', max_length=10),
        ),
    ]
