# Generated by Django 3.2.25 on 2025-01-22 08:00

import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tags', '0004_auto_20250122_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagcategory',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='tagcategory',
            unique_together={('name', 'content_type')},
        ),
    ]
