# Generated by Django 3.2.25 on 2025-01-22 08:05

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_auto_20250122_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'category')},
        ),
    ]
