# Generated by Django 3.2.25 on 2025-01-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_auto_20250122_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagcategory',
            name='input_type',
        ),
        migrations.AddField(
            model_name='tagcategory',
            name='max_tags',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
