# Generated by Django 3.2.25 on 2025-01-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0007_auto_20250122_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagcategory',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
