# Generated by Django 3.2.25 on 2025-01-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0008_tagcategory_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagcategory',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='categories', to='tags.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
    ]
