# Generated by Django 3.2.25 on 2025-01-24 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0010_auto_20250124_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggeditem',
            name='tag_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.tagcategory'),
        ),
    ]
