# Generated by Django 3.2.25 on 2025-01-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0012_alter_taggeditem_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagcategory',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='tagcategory',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
