# Generated by Django 3.2.25 on 2025-02-12 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0013_auto_20250124_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagcategory',
            options={'ordering': ('order', 'name')},
        ),
    ]
