# Generated by Django 3.2.25 on 2025-02-21 22:32

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0014_alter_tagcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=100, unique=True),
        ),
    ]
