# Generated by Django 3.2.25 on 2025-01-17 06:05

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radios', '0007_merge_20220715_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiosession',
            name='config',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
