# Generated by Django 3.2.25 on 2025-01-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0057_auto_20221118_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='record_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='track',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
