# Generated by Django 3.2.25 on 2025-02-20 10:49

from django.db import migrations, models
import funkwhale_api.music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0059_auto_20250124_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='media_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], default='audio', max_length=10),
        ),
        migrations.AddField(
            model_name='track',
            name='resolution',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='media_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], default='audio', max_length=10),
        ),
        migrations.AddField(
            model_name='upload',
            name='video_codec',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='video_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=funkwhale_api.music.models.get_file_path),
        ),
        migrations.AddField(
            model_name='upload',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
