# Generated by Django 3.2.25 on 2025-02-24 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0060_auto_20250220_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='track',
            name='resolution',
        ),
    ]
