# Generated by Django 3.2.25 on 2025-02-24 06:42

from django.db import migrations, models
import funkwhale_api.music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0061_auto_20250224_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadversion',
            name='video_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=funkwhale_api.music.models.get_file_path),
        ),
    ]
