# Generated by Django 3.2.25 on 2025-03-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cover', models.ImageField(upload_to='concert_covers/')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('mux_live_stream_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mux_playback_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
