# Generated by Django 3.2.25 on 2025-03-07 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0062_uploadversion_video_file'),
        ('concerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.artist'),
        ),
    ]
